### ISSUE TITLE
AFL Footyshow Playback Fails 

### ISSUE THREAD

**Issue by manmountain666** [xbmc-catchuptv-au/plugin.video.catchuptv.au.nine#8] opened 2016-06-07 01:49 UTC
[kodi_log.txt](https://github.com/xbmc-catchuptv-au/plugin.video.catchuptv.au.nine/files/301680/kodi_log.txt)

**Comment by guest07** [comment] 2016-06-15 11:25
Duplicate of issue #9

**Closed as completed** 2018-10-16 04:37 UTC
