### ISSUE TITLE
New shows not working

### ISSUE THREAD

**Issue by nestyle** [xbmc-catchuptv-au/plugin.video.catchuptv.au.nine#9] opened 2016-06-07 13:34 UTC
Hi mate
The plugin opens up fine & shows the new shows, but it doesn't play them.
Hoping yourself or @adammw could have a look please.

error that keeps coming up
XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.catchuptv.au.nine/play/

Cheers

[kodi.txt](https://github.com/xbmc-catchuptv-au/plugin.video.catchuptv.au.nine/files/302679/kodi.txt)

**Comment by guest07** [comment] 2016-06-15 10:40
I think this might be because Nine has started using Dynamic Adaptive Streaming over HTTP (DASH) and XBMC/Kodi doesn't support it. Here's an example of a JSON that doesn't play, note the "dash.mpd" file in the url field and M4F videoContainer:

```
{
  "id": 4918170156001,
  "name": "Audition 3",
  "shortDescription": "Simon Cowell, Amanda Holden, Alesha Dixon and David Walliams - once again take their places on the panel to find the most astonishing and exhilarating talent that will entertain the nation and capture the hearts of the world.",
  "videoFullLength": {
    "audioOnly": false,
    "controllerType": "DEFAULT",
    "displayName": "BRGO2016_3_B_HBB.mp4",
    "encodingRate": 500000,
    "frameHeight": 360,
    "frameWidth": 640,
    "id": 4918168579001,
    "referenceId": null,
    "remoteStreamName": null,
    "remoteUrl": null,
    "size": 222085394,
    "uploadTimestampMillis": 1464558620375,
    "url": "http://progressive.netshow.ninemsn.com.au/media2/1622448031001/2016/05/4918168579001/dash.mpd",
    "videoCodec": "H264",
    "videoContainer": "M4F",
    "videoDuration": 3539280
  }
}
```

Update: it looks like Kodi versions 17 upwards can utilise inputstream.mpd:

mapfau/inputstream.mpd
https://github.com/mapfau/inputstream.mpd

Those of us on older XBMC/Kodi versions are probably out of luck.

**Comment by nestyle** [comment] 2016-06-20 10:46
thanks for the info
for now we have to wait & see what happens

**Comment by guest07** [comment] 2016-06-26 10:38
I've read VLC supports DASH so I've tried adding it as an external player by creating ~/.xbmc/userdata/playercorefactory.xml with the following contents and xbmc switches to VLC when I attempt to play a video using the nine catchup add-on but VLC doesn't play it, nor does VLC play it if I open the URL containing dash.mpd directly in VLC so the problem is with VLC not this add-on. I thought I'd post this information in case someone else can figure out how to get VLC to play these steams (it's possible the mpd format 9Now uses is a different version to the one my version (2.1.6) of VLC supports):

```
<?xml version="1.0" encoding="UTF-8"?>
<!--
# Goes inside %APPDATA%\kodi\userdata
-->
<playercorefactory>
  <players>
    <player name="VLC" type="ExternalPlayer" audio="false" video="true">
      <filename>/usr/bin/vlc</filename>
      <hidexbmc>true</hidexbmc>
      <hideconsole>true</hideconsole>
      <warpcursor>none</warpcursor>
    </player>
  </players>
  <rules action="prepend">
    <rule filetypes="mpd" player="VLC" />
  </rules>
</playercorefactory>
```

**Comment by nestyle** [comment] 2016-07-04 13:21
I installed VLC 3.0 nightly build, & copied the mpd link into the network stream & VLC plays the video with no problems. Also the external player option in kodi works.

``` xml
<playercorefactory>
  <players>
    <player name="VLC" type="ExternalPlayer" audio="false" video="true">
      <filename>C:\Program Files\VideoLAN\VLC\vlc.exe</filename>
      <hidexbmc>false</hidexbmc>
      <hideconsole>false</hideconsole>
      <warpcursor>none</warpcursor>
    </player>
  </players>
  <rules action="prepend">
    <rule filetypes="mpd" player="VLC" />
  </rules>
</playercorefactory>
```

**Comment by guest07** [comment] 2016-07-16 09:29
Thanks nestyle, I've managed to get VLC 3 running and successfully playing the steams on my system too (Ubuntu 14.04 - Trusty). As it was a bit of a process, I thought I'd document it here for the benefit of others. I've also modified the playercorefactory.xml file so VLC launches in fullscreen and also enabled the "play and quit" option within VLC so VLC automatically quits when the video has finished playing and XBMC/Kodi is returned to the foreground.

If you're running Ubuntu 15.10, 16.04 or 16.10, simply perform the following procedure:
1. sudo add-apt-repository ppa:videolan/master-daily
2. sudo apt-get update
3. sudo apt-get install vlc

Otherwise, you'll need to build from source using the following procedure:
1. sudo add-apt-repository ppa:videolan/master-daily
2. sudo apt-get update
3. sudo apt-get install git build-essentials libvpdau-dev
4. sudo apt-get build-dep vlc x264
5. git clone git://git.videolan.org/x264.git
6. git clone git://git.videolan.org/vlc.git
7. cd x264
8. ./configure --enable-pic
9. make && sudo make install
10. wget https://libav.org/releases/libav-11.7.tar.xz
11. tar xf libav-11.7.tar.xz
12. cd libav-11.7
13. ./configure --enable-libx264 --enable-gpl --enable-pic --enable-vdpau
14. make && sudo make install
15. cd ../vlc
16. ./bootstrap
17. ./configure --enable-x264 --with-pic --enable-lirc --enable-alsa --enable-vdpau
18. make
19. Set the filename attribute in playercorefactory.xml to the vlc binary in the vlc directory created during this process e.g. /home/user/vlc/vlc

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
# Goes inside %APPDATA%\kodi\userdata
-->
<playercorefactory>
  <players>
    <player name="VLC" type="ExternalPlayer" audio="false" video="true">
      <filename>/home/user/vlc/vlc</filename>
      <args>-f --http-port 8081</args>
      <hidexbmc>true</hidexbmc>
      <hideconsole>true</hideconsole>
      <warpcursor>none</warpcursor>
    </player>
  </players>
  <rules action="prepend">
    <rule filetypes="mpd" player="VLC" />
  </rules>
</playercorefactory>
```

How to shut down computer - Quitting VLC - VideoLAN Wiki
https://wiki.videolan.org/How_to_shut_down_computer/#Quitting_VLC

**Comment by chadmccathie** [comment] 2017-01-09 12:53
First of all amazing work here guys thank you. 
Quick question :  when ' [DRM/UNPLAYABLE]' is showing up on files is this due to the fact a login is required or am i completely off here?

**Comment by adammw** [comment] 2017-01-11 04:29
It's that those shows are protected with DRM, which by its very nature is not supported for playback on open platforms like XBMC. Unless someone finds a way around the DRM or how to run it within XBMC, they won't be supported.

**Comment by guest08** [comment] 2017-05-07 11:12
@glennguy is working on a new version of the 9Now addon, see @andybotting's issue tracking this here: xbmc-catchuptv-au/repo#47, that looks like it will fix the DRM problem for users using Kodi v17, which has the inputsteam addon extension point.

**Closed as completed** 2018-10-16 04:37 UTC
